# Generated by Django 4.0.3 on 2022-04-03 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Szczepionka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwaSzczepionki', models.CharField(max_length=45, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Szczepionki',
            },
        ),
        migrations.CreateModel(
            name='Pacjent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=45)),
                ('nazwisko', models.CharField(max_length=45)),
                ('pesel', models.CharField(max_length=11, unique=True)),
                ('telefon', models.CharField(max_length=9, unique=True)),
                ('szczepionka', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='szczepionki', to='Szczepienia.szczepionka')),
            ],
            options={
                'verbose_name_plural': 'Pacjenci',
            },
        ),
    ]
