# Generated by Django 4.1.1 on 2022-12-25 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Szczepienia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='szczepionka',
            name='dawka',
            field=models.IntegerField(),
        ),
    ]
