# Generated by Django 4.1.1 on 2022-10-14 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Szczepienia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Punkt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.TextField(max_length=80, unique=True)),
                ('miasto', models.TextField(max_length=80, unique=True)),
                ('ulica', models.TextField(max_length=80, unique=True)),
                ('numer', models.TextField(max_length=80, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Punkty szczepień',
            },
        ),
        migrations.AddField(
            model_name='szczepienie',
            name='punkt',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='punkty', to='Szczepienia.punkt'),
        ),
    ]
