# Generated by Django 4.1.1 on 2022-10-15 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Szczepienia', '0002_punkt_szczepienie_punkt'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacjent',
            name='isStaff',
            field=models.BooleanField(default=False),
        ),
    ]
