# Generated by Django 4.0.3 on 2022-04-11 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Szczepienia', '0002_szczepienie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='szczepienie',
            name='idPacjenta',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, related_name='szczepieni', to='Szczepienia.pacjent'),
        ),
    ]
