# Generated by Django 4.1.1 on 2022-12-06 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Szczepienia', '0002_alter_punkt_miasto_alter_punkt_nazwa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='punkt',
            name='centerX',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='punkt',
            name='centerY',
            field=models.FloatField(null=True),
        ),
    ]
