# Generated by Django 4.1.1 on 2022-12-17 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Szczepienia', '0003_punkt_centerx_punkt_centery'),
    ]

    operations = [
        migrations.AddField(
            model_name='szczepionka',
            name='dawka',
            field=models.IntegerField(default=3),
        ),
    ]
