# Generated by Django 4.1.1 on 2022-10-15 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Szczepienia', '0003_pacjent_isstaff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pacjent',
            name='isStaff',
        ),
        migrations.AlterField(
            model_name='pacjent',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
