# Generated by Django 4.0.3 on 2022-04-11 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Szczepienia', '0004_delete_szczepienie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Szczepienie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwaSzczepionki', models.CharField(max_length=45, unique=True)),
                ('idPacjenta', models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, related_name='szczepieni', to='Szczepienia.pacjent')),
            ],
            options={
                'verbose_name_plural': 'Szczepienia',
            },
        ),
    ]
