# Generated by Django 4.1.1 on 2022-10-15 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Szczepienia', '0004_remove_pacjent_isstaff_alter_pacjent_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='szczepienie',
            name='dataSzczepienia',
            field=models.DateField(),
        ),
    ]
