# Generated by Django 4.0.3 on 2022-04-11 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Szczepienia', '0005_szczepienie'),
    ]

    operations = [
        migrations.AddField(
            model_name='szczepienie',
            name='dataSzczepienia',
            field=models.DateField(default='2022-04-09'),
        ),
    ]
