# Generated by Django 4.0.3 on 2022-04-11 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Szczepienia', '0007_alter_szczepienie_idpacjenta_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='szczepienie',
            old_name='idPacjenta',
            new_name='Pacjent',
        ),
    ]
