# Generated by Django 4.0.3 on 2022-04-11 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Szczepienia', '0008_rename_idpacjenta_szczepienie_pacjent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='szczepienie',
            name='nazwaSzczepionki',
        ),
        migrations.AddField(
            model_name='szczepienie',
            name='czyOstatniaDawka',
            field=models.BooleanField(default=False),
        ),
    ]
