# Generated by Django 4.0.3 on 2022-04-11 09:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Szczepienia', '0009_remove_szczepienie_nazwaszczepionki_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='szczepienie',
            name='dataSzczepienia',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
