# Generated by Django 4.0.3 on 2022-04-11 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Szczepienia', '0010_alter_szczepienie_dataszczepienia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='szczepienie',
            old_name='Pacjent',
            new_name='pacjent',
        ),
    ]
