# Generated by Django 4.0.3 on 2022-04-25 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Szczepienia', '0012_zaszczepiony'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zaszczepiony',
            options={'verbose_name_plural': 'Zaszczepieni'},
        ),
    ]
