# Generated by Django 4.0.3 on 2022-04-25 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Szczepienia', '0013_alter_zaszczepiony_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Zaszczepiony',
        ),
    ]
